<a href="https://colab.research.google.com/github/Valeriaya512/Python/blob/main/tidy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## tidy的資料集合

常見的4個非tidy資料：
1. Column其實是質而不是變數 - 使用gather() / pivot_longer()
2. 把變數當值 - 使用spread() / pivot_wider()
3. 多個變數儲存在廷個column中 - 使用separate()
4. 一個變數被分存在columns中 - 使用unite()

| 功能  | 舊寫法      | 新寫法            | 方向      | 常見用途                  |
| --- | -------- | -------------- | ------- | --------------------- |
| 寬轉長 | gather() | pivot_longer() | 一欄變兩欄以上 | 把「國文、英文、數學」變成「科目、分數」  |
| 長轉寬 | spread() | pivot_wider()  | 兩欄以上變多欄 | 把「月份、銷售額」展開成 1月、2月、3月 |

| 函數             | 作用方向  | 主要用途           | 新舊寫法      | 一句話記法        |
| -------------- | ----- | -------------- | --------- | ------------ |
| separate()     | 一欄拆多欄 | 把同一欄中混在一起的資訊拆開 | 常用舊函數，仍可用 | 一欄裡有多個變數，就拆開 |
| unite()        | 多欄合一欄 | 把多個欄位合成一個欄位    | 常用舊函數，仍可用 | 多欄資料要合併，就黏起來 |
| pivot_longer() | 寬轉長   | 把多個欄位變成兩欄以上    | 新版建議用     | 欄位變成列        |
| pivot_wider()  | 長轉寬   | 把一欄中的類別展開成多欄   | 新版建議用     | 列變成欄位        |

In [8]:
# gather: wide data to long data
library(tidyr)

df <- data.frame(
  學生 = c("A", "B", "C"),
  國文 = c(80, 75, 90),
  英文 = c(85, 88, 78),
  數學 = c(92, 70, 84)
)

df

df_long <- gather(df, key = "科目", value = "分數", 國文, 英文, 數學)
df_long

  學生 國文 英文 數學
1 A    80   85   92
2 B    75   88   70
3 C    90   78   84

  學生 科目 分數
1 A    國文 80
2 B    國文 75
3 C    國文 90
4 A    英文 85
5 B    英文 88
6 C    英文 78
7 A    數學 92
8 B    數學 70
9 C    數學 84

In [10]:
# pivot_longer(): wide data to long data
library(tidyr)

df <- data.frame(
  學生 = c("A", "B", "C"),
  國文 = c(80, 75, 90),
  英文 = c(85, 88, 78),
  數學 = c(92, 70, 84)
)

df_long <- pivot_longer(
  df,
  cols = c(國文,英文,數學),
  names_to = "科目",
  values_to = "分數"
)
df_long

  學生 科目 分數
1 A    國文 80
2 A    英文 85
3 A    數學 92
4 B    國文 75
5 B    英文 88
6 B    數學 70
7 C    國文 90
8 C    英文 78
9 C    數學 84

In [11]:
# spread()：long data to wide data
library(tidyr)

df2 <- data.frame(
  學生 = c("A", "A", "A", "B", "B", "B"),
  科目 = c("國文", "英文", "數學", "國文", "英文", "數學"),
  分數 = c(80, 85, 92, 75, 88, 70)
)
df2

df_wide <- spread(df2, key = "科目", value = "分數")
df_wide

  學生 科目 分數
1 A    國文 80
2 A    英文 85
3 A    數學 92
4 B    國文 75
5 B    英文 88
6 B    數學 70

  學生 國文 數學 英文
1 A    80   92   85
2 B    75   70   88

In [17]:
# pivot_wider(): long data to wide data
library(tidyr)

df2 <- data.frame(
  學生 = c("A", "A", "A", "B", "B", "B"),
  科目 = c("國文", "英文", "數學", "國文", "英文", "數學"),
  分數 = c(80, 85, 92, 75, 88, 70)
)

df_wide <- pivot_wider(
  df2,
  names_from = 科目,
  values_from = 分數
)
df_wide

  學生 國文 英文 數學
1 A    80   85   92
2 B    75   88   70

In [19]:
df_wide <- df2 %>% pivot_wider(  # %>%：將左側的運算結果傳遞至右側的第一個參數
  names_from = 科目,
  values_from = 分數
)
df_wide

  學生 國文 英文 數學
1 A    80   85   92
2 B    75   88   70

In [23]:
# separate()：把同一個欄位裡面包含多個資訊拆成多個欄位
library(tidyr)

df <- data.frame(
  id = 1:3,
  姓名性別 = c("小明_男", "小美_女", "小華_男")
)

df2 <- df %>% separate(
  姓名性別,
  into = c("姓名", "性別"),
  sep = "_"
)
df2

  id 姓名 性別
1 1  小明 男
2 2  小美 女
3 3  小華 男

In [26]:
df <- data.frame(
  日期 = c("2026-06-10", "2026-06-11", "2026-06-12")
)

df2 <- df %>%
  separate(
    日期,
    into = c("年", "月", "日"),
    sep = "-"
  )

df2

  年   月 日
1 2026 06 10
2 2026 06 11
3 2026 06 12

In [28]:
# unite()：把多個欄位合併成一個欄位裡面包含多個資訊
df <- data.frame(
  姓名 = c("小明", "小美"),
  性別 = c("男", "女")
)
df2 <- unite(df, "資訊", 姓名, 性別, sep = "_")
df2

  資訊
1 小明_男
2 小美_女

In [46]:
df <- data.frame(
  id = c(1, 2),
  info = c("台北_男", "台中_女"),
  score_math = c(90, 85),
  score_english = c(88, 92)
)
df

df2 <- df %>% separate(
    info,
    into = c("區域", "性別"),
    sep = "_"
    )%>%
    pivot_longer(
    cols = starts_with("score_"),  #把所有score_開頭的欄位挑出來
    names_to = "科目",
    values_to = "分數"
)
df2

  id info    score_math score_english
1 1  台北_男 90         88
2 2  台中_女 85         92

  id 區域 性別 科目          分數
1 1  台北 男   score_math    90
2 1  台北 男   score_english 88
3 2  台中 女   score_math    85
4 2  台中 女   score_english 92

In [48]:
library(tidyr)
library(dplyr)

In [50]:
stock.data <- data.frame(
  stock = c("AAPL", "MSFT"),
  name = c("Apple", "Microsoft"),
  `2026-01-01` = c(100, 200),
  `2026-01-02` = c(102, 205),
  `2026-01-03` = c(101, 210)
)

stock.data.colnames <- colnames(stock.data)  #把stock.data的所有欄名存到stock.data.colnames。這樣後面就可以用欄名的位置來挑欄位，不用一個一個手寫

#library(tidyr)
#library(dplyr)

stock.data_long <- stock.data %>%
  gather(
    key = "date",
    value = "price",
    stock.data.colnames[3:ncol(stock.data)]  #表示從第3欄開始到最後一欄，都拿來做轉換
  )

stock.data_long

  stock name      date        price
1 AAPL  Apple     X2026.01.01 100
2 MSFT  Microsoft X2026.01.01 200
3 AAPL  Apple     X2026.01.02 102
4 MSFT  Microsoft X2026.01.02 205
5 AAPL  Apple     X2026.01.03 101
6 MSFT  Microsoft X2026.01.03 210